[package]
name = "orderbook-rs"
version = "0.1.0"
authors = ["unknown <inv2004@gmail.com>"]

[dependencies]
uuid = { version = "0.6.5", features = ["v4"] }

[dev-dependencies]
coinbase-pro-rs = "0.2.2"
futures = "0.1.23"
tokio = "0.1.8"
tokio-tungstenite = "0.6.0"
failure = "0.1.2"
